service: serverless-example

plugins: 
  - serverless-offline
  - serverless-offline-ssm

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  environment:
    SKIP_SSM: 1

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  serverless-offline-ssm:
    stages:
      - dev
    ssm:
      'sample.key': 'test'